version: "3.4"

services:
  api:
    depends_on:
      - app_redis
    image: gio_ai_api:latest
    deploy:
      replicas: 4
      restart_policy:
        condition: any
    ports:
      - mode: ingress
        target: 3000
        published: 3000
        protocol: tcp
    working_dir: /app

  app_redis:
    image: redis:latest
    deploy:
      restart_policy:
        condition: any
    ports:
      - mode: ingress
        target: 6379
        published: 6379
        protocol: tcp