version: "3.4"

services:
  api:
    depends_on:
      - app_redis
    image: gio_ai_api:latest
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    deploy:
      replicas: 4
      restart_policy:
        condition: any
    ports:
      - mode: ingress
        target: 3000
        published: 3000
        protocol: tcp
    working_dir: /app
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "us-east-1"
        awslogs-group: "puzzletherapy_ai_api_production"
        awslogs-stream: "main"

  app_redis:
    image: redis:latest
    deploy:
      restart_policy:
        condition: any
    ports:
      - mode: ingress
        target: 6379
        published: 6379
        protocol: tcp