###
// @no-log
#POST https://api.selfcouture.co/generator/main
GET http://localhost:3000/test/proc
Accept: application/json
APP-API-KEY: 8bc3e33c3fe691dec8816ebb1761fa62a81bd1c0086034e217668f1cc515


###
// @no-log
#POST https://api.selfcouture.co/generator/main
GET http://localhost:3000/generator/generations/some_user_id_here
Accept: application/json
APP-API-KEY: 8bc3e33c3fe691dec8816ebb1761fa62a81bd1c0086034e217668f1cc515


###
// @no-log
#GET http://localhost:3000/test/image?link=https://cdn.midjourney.com/f0f2aae6-5196-49e5-bcb0-77222a936a54/0_0.png&name=test_name_1233.png
GET https://api.selfcouture.co/test/image?link=https://cdn.midjourney.com/f0f2aae6-5196-49e5-bcb0-77222a936a54/0_0.png&name=test_name_12335.png
Accept: application/json
APP-API-KEY: 8bc3e33c3fe691dec8816ebb1761fa62a81bd1c0086034e217668f1cc515


###
// @no-log
#POST https://api.selfcouture.co/generator/main
GET http://localhost:3000/generator/images/some_user_id_here
Accept: application/json
APP-API-KEY: 8bc3e33c3fe691dec8816ebb1761fa62a81bd1c0086034e217668f1cc515


###
// @no-log
#POST https://api.selfcouture.co/generator/main
POST http://localhost:3000/generator/main
Accept: application/json
Content-Type: application/json
APP-API-KEY: 8bc3e33c3fe691dec8816ebb1761fa62a81bd1c0086034e217668f1cc515

{
  "prompt": "Farm with animals and grape",
  "email": "dimauuvin@gmail.com",
  "userId": "some_user_id_here",
  "redirectUrl": "https://api.selfcouture.co/api/docs"
}


###
// @no-log
GET http://localhost:4050/generator/images/some_user_id_here?perPage=1&page=1
Accept: application/json
APP-API-KEY: 8bc3e33c3fe691dec8816ebb1761fa62a81bd1c0086034e217668f1cc515


###
// @no-log
GET http://localhost:4050/test/api
Accept: application/json


###


###
// @no-log
POST http://localhost:4050/generator/main
Accept: application/json
Content-Type: application/json
APP-API-KEY: 8bc3e33c3fe691dec8816ebb1761fa62a81bd1c0086034e217668f1cc515

{
  "prompt": "Family of farmers harvesting grapes",
  "email": "test@email.com",
  "userId": "some_user_id_here",
  "redirectUrl": "https://api.selfcouture.co/api/docs"
}


###
// @no-log
GET http://localhost:4050/generator/images/test-hui
Accept: application/json
APP-API-KEY: 8bc3e33c3fe691dec8816ebb1761fa62a81bd1c0086034e217668f1cc515

###
// @no-log
POST http://localhost:4050/generator/main
Accept: application/json
APP-API-KEY: 8bc3e33c3fe691dec8816ebb1761fa62a81bd1c0086034e217668f1cc515
Content-Type: application/json

{
  "prompt": "test",
  "email": "test@gmail.com",
  "userId": "Tes"
}



###
// @no-log
POST http://localhost:4050/generator/upscale-image
Content-Type: application/json
Accept: application/json

{
  "callSid": "CA8a0af6ed2b02ba67b885a5f5842cdbdc",
  "carName": "NEW CAR NAME 1"
}
