###
// @no-log
#POST https://api.selfcouture.co/generator/main
POST http://localhost:3000/generator/main
Accept: application/json
Content-Type: application/json
APP-API-KEY: 8bc3e33c3fe691dec8816ebb1761fa62a81bd1c0086034e217668f1cc515

{
  "prompt": "New Year's Eve in New York City with warm ambient lighting illuminating the streets, detailed depiction of festive decorations, and lively crowds celebrating. Type of Image: Photograph, Environment: Outdoor, Camera: Front view, Shot: Wide angle, Render: 4K resolution, (((vibrant colors))), Lighting: Warm ambient light with golden streetlights, Lens: 35mm.",
  "email": "gio@nusagi.co",
  "userId": "some_user_id_here",
  "redirectUrl": "https://api.selfcouture.co/api/docs"
}


###
// @no-log
GET http://localhost:4050/generator/images/some_user_id_here?perPage=1&page=1
Accept: application/json
APP-API-KEY: 8bc3e33c3fe691dec8816ebb1761fa62a81bd1c0086034e217668f1cc515


###
// @no-log
GET http://localhost:4050/test/api
Accept: application/json


###


###
// @no-log
POST http://localhost:4050/generator/main
Accept: application/json
Content-Type: application/json
APP-API-KEY: 8bc3e33c3fe691dec8816ebb1761fa62a81bd1c0086034e217668f1cc515

{
  "prompt": "Family of farmers harvesting grapes",
  "email": "dimavfox@gmail.com",
  "userId": "some_user_id_here",
  "redirectUrl": "https://api.selfcouture.co/api/docs"
}


###
// @no-log
GET http://localhost:4050/generator/images/test-hui
Accept: application/json
APP-API-KEY: 8bc3e33c3fe691dec8816ebb1761fa62a81bd1c0086034e217668f1cc515

###
// @no-log
POST http://localhost:4050/generator/main
Accept: application/json
APP-API-KEY: 8bc3e33c3fe691dec8816ebb1761fa62a81bd1c0086034e217668f1cc515
Content-Type: application/json

{
  "prompt": "test",
  "email": "test@gmail.com",
  "userId": "Tes"
}



###
// @no-log
POST http://localhost:4050/generator/upscale-image
Content-Type: application/json
Accept: application/json

{
  "callSid": "CA8a0af6ed2b02ba67b885a5f5842cdbdc",
  "carName": "NEW CAR NAME 1"
}
